[hooks]
pre-commit = "cargo fmt --all --check -- --config imports_granularity=Module,group_imports=StdExternalCrate && cargo clippy --all-targets && cargo test && cargo deny check licenses"

[logging]
verbose = true
